name: 'API Change Notifier'
description: 'Analyzes project files for API changes'

inputs:
  target-dir:
    description: 'Path to the project files'
    required: true
    default: '.'
  version:
    description: 'Version of the notifier to run'
    required: true
    default: 'v1.0.6'
runs:
  using: 'composite'
  steps:
    - name: Download the JAR from Releases
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # 1. Use the gh tool to download the asset specifically
        # This is safer than curl for private or public repos
        gh release download ${{ inputs.version }} \
          --repo AgrwalNipun/api_change_notifier \
          --pattern "api-change-notifier.jar" \
          --dir "${{ github.action_path }}"

        # 2. Rename it to a standard name for the next step
        mv "${{ github.action_path }}/api-change-notifier.jar" "${{ github.action_path }}/notifier.jar"

    - name: Execute the JAR
      shell: bash
      run: |
        # Use quotes to handle paths with spaces safely
        java -jar "${{ github.action_path }}/notifier.jar" "${{ inputs.target-dir }}"
