name: 'API Change Notifier'
description: 'Analyzes project files for API changes'

inputs:
  target-dir:
    description: 'Path to the project files'
    required: true
    default: '.'
  version:
    description: 'Version of the notifier to run'
    required: true
    default: 'v1.0.3'

runs:
  using: 'composite'
  steps:
    - name: Download the JAR from Releases
      shell: bash
      # Downloads the JAR file directly to the action's working path
      run: |
        curl -sL -o ${{ github.action_path }}/notifier.jar \
        https://github.com/AgrwalNipun/api_change_notifier/releases/download/${{ inputs.version }}/api-change-notifier.jar

    - name: Execute the JAR
      shell: bash
      run: java -jar ${{ github.action_path }}/notifier.jar ${{ inputs.target-dir }}